import { render } from "@testing-library/react";
import { describe, expect, it } from "vitest";

import { InlineMarkdown, Markdown } from "./markdown";

// The description from the task in Daniel's screenshot, shortened.
const AGENT_DESCRIPTION = `> _This was generated by AI from a grilling session (2026-09-25)._

**Repo:** \`FigurePOS/fgr-service-orders\`. Branch \`fgr3-7548\`.

**What to build:**
- **Sale.** The main row's \`payment_type\` becomes \`payload.paymentType ?? card\`.
  - Tip rows stay Card.
- **Guard:** card-program Sale with \`tipAmount > 0\` throws.`;

describe("Markdown", () => {
  it("renders what agents write instead of showing the markers", () => {
    const { container } = render(<Markdown>{AGENT_DESCRIPTION}</Markdown>);

    expect(container.textContent).not.toContain("**");
    expect(container.textContent).not.toContain("`");
    expect(container.querySelector("blockquote em")?.textContent).toBe(
      "This was generated by AI from a grilling session (2026-09-25).",
    );
    expect(container.querySelector("p strong")?.textContent).toBe("Repo:");
    expect(container.querySelectorAll("code")).toHaveLength(5);
    expect(container.querySelectorAll("ul > li")).toHaveLength(3);
    expect(container.querySelector("ul ul li")?.textContent).toBe(
      "Tip rows stay Card.",
    );
  });

  it("keeps a single newline as a line break, as GitHub comments do", () => {
    const { container } = render(<Markdown>{"Done: lint\nLeft: CI"}</Markdown>);
    expect(container.querySelectorAll("p")).toHaveLength(1);
    expect(container.querySelector("p br")).not.toBeNull();
  });

  it("starts headings below the page's own", () => {
    const { container } = render(<Markdown>{"# Context\n\n## Plan"}</Markdown>);
    expect(container.querySelector("h1, h2")).toBeNull();
    expect(container.querySelector("h3")?.textContent).toBe("Context");
    expect(container.querySelector("h4")?.textContent).toBe("Plan");
  });

  it("renders tables and read-only checklists", () => {
    const { container } = render(
      <Markdown>
        {"| a | b |\n| - | - |\n| 1 | 2 |\n\n- [x] done\n- [ ] open"}
      </Markdown>,
    );
    expect(container.querySelectorAll("td")).toHaveLength(2);
    const boxes = container.querySelectorAll<HTMLInputElement>(
      "input[type=checkbox]",
    );
    expect([...boxes].map((box) => [box.checked, box.disabled])).toEqual([
      [true, true],
      [false, true],
    ]);
  });

  it("never renders raw HTML or script URLs", () => {
    const { container } = render(
      <Markdown>
        {
          '<script>alert(1)</script>\n\n<img src=x onerror="alert(1)">\n\n[click](javascript:alert(1))'
        }
      </Markdown>,
    );
    expect(container.querySelector("script, img, [onerror]")).toBeNull();
    expect(container.querySelector("a")?.getAttribute("href")).toBe("");
  });

  it("opens outside links in a new tab without handing over the page", () => {
    const { container } = render(
      <Markdown>
        {"[PR](https://github.com/o/r/pull/1) and [T-3](/tasks/T-3)"}
      </Markdown>,
    );
    const [outside, inside] = container.querySelectorAll("a");
    expect(outside?.getAttribute("target")).toBe("_blank");
    expect(outside?.getAttribute("rel")).toBe("noreferrer noopener");
    expect(inside?.getAttribute("target")).toBeNull();
  });

  it("shows an image as a link rather than loading it", () => {
    const { container } = render(
      <Markdown>{"![chart](https://example.com/a.png)"}</Markdown>,
    );
    expect(container.querySelector("img")).toBeNull();
    expect(container.querySelector("a")?.textContent).toBe("chart");
  });
});

describe("InlineMarkdown", () => {
  it("keeps a criterion on one line: code and emphasis, no blocks", () => {
    const { container } = render(
      <InlineMarkdown>{"# `pnpm verify` passes **locally**"}</InlineMarkdown>,
    );
    expect(container.querySelector("h1, h3, p")).toBeNull();
    expect(container.querySelector("code")?.textContent).toBe("pnpm verify");
    expect(container.querySelector("strong")?.textContent).toBe("locally");
  });
});
