/** Identity of an entity, generated by the domain rather than by the database. */
export class UniqueId {
  private constructor(readonly value: string) {}

  static create(value?: string): UniqueId {
    return new UniqueId(value ?? crypto.randomUUID());
  }

  equals(other?: UniqueId): boolean {
    return other instanceof UniqueId && other.value === this.value;
  }

  toString(): string {
    return this.value;
  }
}
